language: java
jdk: oraclejdk8
dist: trusty

script:
  - mvn testrunner:testplugin -Ddetector.detector_type=random-class-method -Ddt.randomize.rounds=10 -Ddt.detector.original_order.all_must_pass=false
